project:
  type: website
  output-dir: docs

bibliography: references.bib

website:
  title: "Microbiome x Cardiometabolic Health"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Methods
      - href: results.qmd
        text: Results
      - href: team.qmd
        text: Team

  page-footer:
    left: "BNFO 420 • VCU • End of Manuscript"
    right: "Built with Quarto • Manuscript v1.0"

format:
  html:
    theme:
      - cosmo
      - assets/theme.scss
    toc: true
    number-sections: true
    smooth-scroll: true

execute:
  echo: true
  warning: false
  message: false

